---
title: Testing the motor and cognitive foundations of Paleolithic social transmission
author: 
- Justin Pargeter^[Department of Anthropology, New York University, New York, NY, USA; Palaeo-Research Institute, University of Johannesburg, Auckland Park, South Africa; justin.pargeter@nyu.edu]
- Megan Beney Kilgore^[Department of Anthropology, Emory University, Atlanta, GA, USA; megan.elizabeth.beney@emory.edu]
- Cheng Liu^[Department of Anthropology, Emory University, Atlanta, GA, USA; raylc1996@outlook.com]
- Dietrich Stout^[Department of Anthropology, Emory University, Atlanta, GA, USA; dwstout@emory.edu]
abstract: "Stone tools provide key evidence of human cognitive evolution but remain difficult to interpret. Toolmaking skill-learning in particular has been understudied even though: 1) the most salient cognitive demands of toolmaking should occur during learning, and 2) variation in learning aptitude would have provided the raw material for any past selection acting on tool making ability. However, we actually know very little about the cognitive prerequisites of learning under different information transmission conditions that may have prevailed during the Paleolithic. This paper presents results from a pilot experimental study to trial new experimental methods for studying the effect of learning conditions and individual differences on Oldowan flake-tool making skill acquisition. We trained 23 participants for 2 hours to make stone flakes under two different instructional conditions (observation only vs. direct active teaching) employing appropriate raw materials, practice time, and real human interaction. Participant performance was evaluated through analysis of the stone artifacts produced. Performance was compared both across experimental groups and with respect to individual participant differences in grip strength, motor accuracy, and cognitive function measured for the study. Our results show aptitude to be associated with fluid intelligence in a verbally instructed group and with a tendency to use social information in an observation-only group. These results have implications for debates surrounding the cumulative nature of human culture, the relative contributions of knowledge and know-how for stone tool making, and the role of evolved psychological mechanisms in “high fidelity” transmission of information, particularly through imitation and teaching.\\par \\textbf{Keywords:} Oldowan; Stone toolmaking; Social learning; Individual variation; Cognitive aptitudes; Motor skills"
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \linenumbers
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
---

# Introduction

Stone tools have long been seen as a key source of evidence for understanding human behavioral and cognitive evolution [@darwin1871; @oakley1949; @washburn1960]. Pathbreaking attempts to infer specific cognitive capacities from this evidence largely focused on the basic requirements of tool production [@isaac1976; @wynn1979; @gowlett1984; @wynn2004]. More recently, increasing attention has been directed to the processes and demands of stone tool making skill acquisition [@roux1995; @stout2002; @stout2005; @geribàs2010; @nonaka2010; @stout2011; @putt2014; @hecht2015a; @duke2015; @morgan2015; @stout2015; @lombao2017; @putt2017; @cataldo2018; @putt2019; @pargeter2019; @pargeter2020]. This is motivated by the expectation that the most salient cognitive demands of tool making should occur during learning rather than routine expert performance [@stout2015] and by interest in the relevance of different social learning mechanisms such as imitation [@rein2014; @stout2019], emulation [@tehrani2008; @wilkins2018], and language [@ohnuma1997; @putt2014; @morgan2015; @lombao2017; @putt2017; @cataldo2018] to the reproduction of Paleolithic technologies.

Studies investigating these questions have used a range of different experimental designs (e.g., varying technological goals/instructions, training times, raw materials, live vs. recorded instruction, lithic/skill assessment metrics, pseudo-knapping tasks etc.) and reached disparate conclusions regarding the neurocognitive and social foundations of skill acquisition. It is plausible that these discordant results reflect actual diversity in how humans acquire and master stone tool making skills. However, this failure of results to generalize across artificial experimental manipulations [[cf](cf.%20Yarkoni%202020). @yarkoni2020] also raises doubts regarding the external validity [@eren2016] of conclusions with respect to real-world Paleolithic learning contexts. To address this, we conducted an exploratory study that draws on lessons from previous research in an attempt to balance the pragmatic and theoretical tradeoffs inherent in experimental studies of stone knapping skill acquisition [@pargeter2019; @stout2015].

Learning real-world skills like stone knapping is highly demanding of time and materials and difficult to control experimentally without sacrificing generalizability to real world conditions. Prior efforts have attempted to navigate these challenges by using various combinations of 1) inauthentic raw materials that are less expensive, easier to standardize, and/or easier to knap, 2) video-recorded instruction that is uniform across participants and less demanding of experimenter time, 3) short learning periods, 4) small sample sizes, and 5) single learning conditions. The difficulty of interpreting results from this growing literature led Stout and Khreisheh [-@stout2015: 870, emphasis original] to call for "studies with sufficient sample sizes to manipulate learning conditions (e.g. instruction, motivation) and assess individual variation (e.g. performance, psychometrics, neuroanatomy) that *also* have realistic learning periods." The current study attempts to strike a viable balance between these demands by investigating early-stage learning of a relatively simple technology (least effort, "Oldowan," flake production [@reti2016; @shea2016] under two instructional conditions while collecting data on individual differences in strength, coordination, cognition, social learning, self-control, and task engagement. Unlike any previous study, this allows us to address the likelihood that group effects of training conditions might be impacted by interactions with individual participant differences in aptitude, motivation, or learning style.

We focus on early stage learning because it has been found to be relatively rapid, variable across individuals, and predictive of later outcomes [@pargeter2019; @stout2015; @putt2019], and thus provides a reasonable expectation of generating meaningful data on skill and learning variation while minimizing training costs. Moreover, understanding the minimum training times necessary to detect changes in tool making skill will help archaeologists design more realistic and cost-effective experiments. To further manage costs, we limited our study to only two learning conditions (observation only vs. active teaching). This targets a key controversy in human evolution, namely the origins of teaching and language [@gärdenfors2017; @morgan2015], while avoiding highly artificial manipulations of dubious relevance to real-world Paleolithic learning. These choices allowed us to invest more in other aspects of research design that we identified as theoretically important, including measurement of individual differences in cognition and behavior, inclusion of an in-person, fully interactive teaching condition, and use of naturalistic raw materials. Sample size remained small in this internally funded exploratory study but could easily be scaled up at funding levels typical of pre- and post-doctoral research grants in archaeology.

## Individual Differences

"*The many slight differences... being observed in the individuals of the same species inhabiting the same confined locality, may be called individual differences... These individual differences are of the highest importance to us, for they are often inherited ... and they thus afford materials for natural selection to act on and accumulate...*" [@darwin1859, Chapter 2]

Individuals vary in aptitude and learning style for particular skills [@jonassen1993] but this has largely been ignored in studies of knapping skill acquisition, which have instead focused on group effects of different experimental conditions. There are good pragmatic reasons for this, as individual difference studies typically require larger sample sizes and additional data collection. However, overlooking these distinctions is not ideal since individual differences can provide valuable insight into the mechanisms, development, and evolution of cognition and behavior [@boogert2018]. In particular, patterns of association between cognitive traits and behavioral performance can be used to test hypotheses about the cognitive demands of learning particular skills and the likely targets of natural selection acting on aptitude. More prosaically, individual differences can introduce an unexamined and uncontrolled source of variation in group level results. This is especially true in the relatively small "samples of convenience" typical of experimental archaeology.

While testing hypotheses in evolutionary cognitive archaeology remains a considerable challenge [@wynn2017], investigation of individual variation in modern research participants represents one promising direction. For any particular behavior of archaeological interest, it is expected that standing variation in modern populations should remain relevant to normal variation in learning aptitude. The presence of trait variation without impact on learning aptitude would provide strong evidence against the plausibility of the proposed evolutionary relationship. An absence of variation (i.e., past fixation and rigorous developmental canalization) is not expected given the known variability of human brains and cognition [@sherwood2017; @barrett2020]. Any confirmatory findings of trait-aptitude correspondence would then have the testable implication that humans should be evolutionarily derived along the same dimension [e.g. @hecht2015b].

To date, a small number of "neuroarchaeological" studies have reported associations between individual knapping performance and brain structure or physiological responses. Hecht et al. [-@hecht2015a] reported training-related changes in white matter integrity (fractional anisotropy [FA]) that correlated with individual differences in practice time and striking accuracy change. The regional patterning of FA changes also varied across individuals, with only those individuals who displayed early increases in FA under the right ventral precentral gyrus (premotor cortex involved in movement planning and guidance) showing striking accuracy improvement over the training period. Putt et al. [-@putt2019] similarly found that the proportion of flakes to shatter produced by individuals during handaxe making correlated with dorsal precentral gyrus (motor cortex) activation. Pargeter et al. [-@pargeter2020] used a flake prediction paradigm [modeled after @nonaka2010] to confirm that striking force and accuracy are important determinants of handaxe-making success. These findings all point to the central role of perceptual-motor systems [@stout2007] and coordination [@roux1995] in knapping skill acquisition. In addition, Putt et al. [-@putt2019] also found successful flake production to be associated with prefrontal (working memory/cognitive control) activation and Stout et al. [-@stoutCognitiveDemandsLower2015] found that prefrontal activation correlated with success at a strategic judgement (platform selection) task which in turn was predictive of success at out-of-scanner handaxe production. Such investigations are thus starting to chart out the more specific contributions of different neural systems to particular aspects of knapping skill acquisition. To date, however, the cognitive/functional interpretation of systems identified in this manner has largely relied on informal reverse inference (reasoning backward from observed activations to inferred mental processes) from published studies of other tasks that activated the same regions, an approach which is widely regarded as problematic [@poldrack2011].

Here we take a more direct, psychometric approach to measuring individual differences in perceptual-motor coordination and cognition. Psychometric instruments (e.g., tasks, questionnaires) are designed to assess variation in cognitive traits and states, such as fluid intelligence, working memory, attention, motivation, and personality, that have been of theoretical interest to cognitive archaeologists [e.g., @wynn2016]. It is thus surprising that they have been almost entirely neglected in experimental studies of knapping skill. In the only published example we are aware of, Pargeter et al. [-@pargeter2019] reported significant effects of variation in planning and problem solving (Tower of London test [@shallice1982]) and cognitive set shifting (Wisconsin Card Sort test [@grant1948]) on early stage handaxe learning. Of course, cognition is not the only thing that can affect knapping performance. Flake prediction experiments highlight the importance of regulating movement speed/accuracy trade-offs [@nonaka2010; @pargeter2020] and studies of muscle recruitment [@marzke1998] and manual pressure [@williams-hatala2018; @key2018] during knapping highlight basic strength requirements. Along these lines, Key and Lycett [-@key2019] found that individual differences in hand size, shape, and especially grip strength were better predictors of force loading during stone tool use than were attributes of the tools themselves. However, we are unaware of any such studies of biometric influences on variation in knapping success. Finally, the time and effort demands of knapping skill acquisition suggest that differences in personality (e.g., self-control and "grit" [@pargeter2019], motivation [@stout2002], and social vs. individual learning strategies [@miu2020] might also affect learning outcomes. We are again unaware of any previous studies that have assessed such effects. In this study, we assessed all participants with a battery of tests including grip strength, movement speed/accuracy, spatial working memory, fluid intelligence, self-control, tendency to use social information, and motivation/engagement with the tool making task. We were particularly interested in the possibility that these variables might not only impact learning generally, but might also have different effects under different learning conditions.

## Teaching, Language, and Tool Making

“*A creature that learns to make tools to a complex pre-existing pattern...must have the kind of abstracting mind that would be of high selective value in facilitating the development of the ability to communicate such skills by the necessary verbal acts.*”[@montagu1976: 267]

Possible links between tool making and language have been a subject of speculation for nearly 150 years [@engles2003[1873]], if not longer [@hewes1993], although compelling empirical tests have remained elusive. Over 25 years ago, Toth and Schick [-@toth1993] suggested that experiments teaching modern participants to make stone tools in verbal and non-verbal conditions could test the importance of language in the social reproduction of Paleolithic technologies. Ohnuma et al. [-@ohnuma1997] were the first to implement this suggestion in a study of Levallois flake production, followed by more recent studies of handaxe making [@putt2014; @putt2017] and simple flake production [@morgan2015; @cataldo2018; @lombao2017]. This reflects recent interest in the hypothesis that language might be an adaptation for teaching [e.g., @laland2017; @stout2012]. Teaching and learning demands of Paleolithic tool making would thus provide evidence of selective contexts favoring language evolution [@stout2010; @morgan2015; @montagu1976].

Toth and Schick [-@toth1993] were, however, careful to point out that extinct hominid learning strategies and capacities might differ from modern experimental participants. Even leaving aside potential species differences in social learning [cf. @morgan2015; @stout2019], reliance on explicit verbal instruction varies widely across modern human societies [e.g., @boyette2017]. The WEIRD (Western, educated, industrialized, rich, democratic [@henrich2010]) teachers and learners typical of knapping experiments arguably represent an extreme bias toward such instruction. Simply instructing such participants not to speak during an experiment (or to demonstrate but not gesture, etc. [@morgan2015]) is likely to underestimate the efficacy of non-verbal teaching and learning in cultural contexts where it is more common, let alone in a hypothetical pre-linguistic hominid species.

Such concerns are exacerbated in experiments using pre-recorded instructional videos or extremely short training periods. Video does not allow the interactive teaching that is favored even in formal academic knapping classes [e.g., @shea2015] and is almost certainly typical of traditional learning contexts [e.g., @stout2002]. It is not known how video presentation affects the efficacy of teaching generally, or the relative effectiveness of different forms of instruction. Going further, some experiments have manipulated the presence/absence of verbal instruction by presenting the same video with and without sound [@putt2017] or the sound track without the video [@cataldo2018]. While this provides experimental control, it does not allow the instructor to adjust their multi-modal [@levinson2014] communication strategies as they would naturally do, for example through pointing and pantomime. To simply remove a communication channel without allowing any such adaptation is highly artificial and risks generating results that cannot be generalized beyond the specific context of the experiment [@yarkoni2020]. Similarly, unnaturally short training periods (e.g., 5-15 minutes [@morgan2015; @lombao2017]) might misrepresent the relative efficacy of different teaching strategies under more realistic conditions [@whiten2015; @stout2015]. Even the longest training times to date [@stout2015; @pargeter2019] have not produced knapping skills comparable to relevant archaeological examples, and were achieved by limiting sample size and using only one teaching condition.

For these reasons, we sought to explore a middle path between experimental expedience and realism by limiting our experiment to two relatively naturalistic learning conditions and a moderate learning period of two hours. As in previous experiments [@stout2011; @hecht2015a; @pargeter2019] the first condition was unrestricted, interactive instruction in small groups, essentially reproducing the "natural" teaching/learning context familiar [cf. @shea2015] to our WEIRD instructor and student participants. The second condition allowed observation only, with the experimenter visible making flakes but not interacting in any way with learners. This absence of teaching is again a familiar social context for our participants and did not require any novel behaviors from the instructor. It matches the "imitation/emulation" condition of Morgan et al. [-@morgan2015] although we make no assumptions regarding learning mechanisms. We did not include a "reverse engineering" or "end-state emulation" condition in which only finished products were visible. This has been advocated as an important baseline or control condition [@whiten2015] to distinguish observational from individual learning, but is not likely to model any typical Paleolithic learning context nor to stand as an adequate proxy for the cognition of hominid species with different social learning capacities. There is no reason to assume neurocognitive and behavioral processes of reverse-engineering problem solving in modern humans [e.g., @allen2020] approximate the social learning processes of hominids with more ape-like action observation/imitation capacities [@hecht2013a; @hecht2013b; @stout2019].

We selected a two-hour learning period for both pragmatic and theoretical reasons. Pargeter et al. [@pargeter2019] found that even \~90 hours of fully interactive instruction and practice was insufficient to achieve handaxe-making skills comparable to the later Acheulean site of Boxgrove [@garcía-medrano2019; @stout2014], and estimated actual time to mastery as ranging from 121 to 441 hours for different participants. However, they observed the greatest, fastest, and most individually variable skill increases during the first 20 hours of practice. In addition, initial performance was moderately correlated with later achievement. This suggests that studying early-stage learning may be a pragmatic alternative, especially for research investigating individual differences in aptitude. Studies of simple flake production similarly document large initial variation [@stout2015] and rapid early progress [@stout2015; @putt2019; @stoutKnappingSkillEarliest2006]. We designed the current study to test the utility of studying learning and variation during the first two hours of simple flaking instruction/practice, in hopes of finding a viable compromise between experimental realism and cost

## Raw materials and knapping skill

Lithic raw materials vary in size, shape, and fracture mechanical properties that affect the difficulty of achieving different knapping goals [@eren2014]. Unfortunately, it can be difficult and/or expensive to procure authentic raw materials. Experimental studies of knapping skill have often used proxy materials such as flint [@morgan2015; @nonaka2010; @cataldo2018], limestone [@stoutKnappingSkillEarliest2006], porcelain [@khreisheh2013], or heat-treated chert [@putt2014; @putt2017; @putt2019]to model Oldowan and early Acheulean technologies executed in other materials. As well as being more readily available, these proxies are generally easier to knap. This has the benefit of reducing required practice time, but it is unclear how it might affect learning demands more generally or the efficacy of different learning conditions/strategies specifically.

To address this, some studies have attempted to more closely match experimental and archaeological raw material types [@stout2011; @duke2015; @pargeter2019]. However, raw materials vary across individual clasts within as well as between types. This has led to interest in standardizing experimental core morphology [@nonaka2010] and composition, even if this means using artificial materials such as porcelain [@khreisheh2013], brick [@geribàs2010; @lombao2017], or foam blocks [@schillinger2014]. Such manipulations enhance experimental control and internal validity [@eren2016] at the expense of external generalizability to actual archaeological conditions. Specifically, they allow more robust results from smaller samples but eliminate a core element of real-world knapping skill: the ability to produce consistent results from variable materials [@pelegrin1990; @stout2013]. For example, Pargeter et al. [-@pargeter2020] found that predicting specific flaking outcomes on actual handaxe preforms was both more difficult and less technologically important than expected from previous work with standardized, frustum-shaped cores [@nonaka2010]. The alternative to control is to incorporate raw material size, shape, and composition as experimental variables [e.g., @stout2019]. This allows consideration of raw material selection and response to variation as aspects of skill but correspondingly increases the sample sizes required to identify patterning. In considering these issues, we again chose to explore a middle path between pragmatism and realism by employing commercially purchased basalt similar to that known from East African Oldowan sites, allowing clast size and shape to vary within set limits, and selecting the particular clasts provided to each participant to approximate the same distribution.

\

# Materials and Methods

This research was approved by the Emory Institutional Review Board (IRB00113024). All participants provided written informed consent and completed a video release form (<https://databrary.org/support/irb/release-template.html>).

## Participants

Twenty-four adult participants with no prior stone knapping experience were recruited from the Emory community using paper fliers and e-mail listserv advertisements. We were unable to replace one participant who failed to attend their scheduled session, resulting in a total sample of 23. Eleven participants (6 female, 5 male) completed the Untaught condition and 12 (8 female, 4 male) completed the Taught condition.

## Study Visit

Participants were asked to visit the Paleolithic Technology Lab at Emory University to complete one three-hour session. Participants were scheduled to attend in six groups of four, however one of these groups had only three participants due to a no-show on the day of the experiment. Each visit began with the collection of individual differences measures, which took approximately one hour. After that, participants undertook 105 minutes (two hours minus a 15-minute break after 1 hour) of stone tool making practice. This session was video-recorded, and all lithic products were collected. After the tool making task, participants completed an "exit questionnaire" comprising the Intrinsic Motivation Inventory (see below).

Participants were compensated for their time with a \$30 gift card. They also had the opportunity to earn a performance bonus of \$5, \$10, \$15 or \$20 on the gift card. They were told that this bonus would depend on "how well they did" on the last core of their practice session. The actual performance measure was not specified, but in order to allow on the spot payment a simple measure of the percentage of starting weight removed from the final core was used such that: \> 30% earned \$5, \> 40% earned \$10, \> 50% earned \$15, \> 75% earned \$20.

## Individual Difference Measures

We used five individual difference measures for this study:

1) Grip strength was measured in kilograms using an electronic hand dynamometer (Camry EH101). Strength was measured twice and the higher value recorded. Grip strength is a simple measure that is well correlated with overall muscular strength [@wind2010] and a range of other health and fitness measures [@sasaki2007]. It is hypothesized to be relevant to generating kinetic energy for fracture initiation [@nonaka2010] as well as control and support of the hammerstone [@williams-hatala2018] and core [@faisal2010; @key2015].

2)  Motor accuracy was assessed using a "Fitts Law" reciprocal tapping task. Fitts Law describes the trade-off between speed and accuracy in human movement, classically measured by tapping back and forth between two targets of varying size and spacing [@fitts1954]. Archaeologists have proposed [@stout2002; @pargeter2020] that management of this trade-off is critical to the accurate application of appropriate force seen in skilled knapping [@nonaka2010; @roux1995]. We implemented this test on a Surface Pro tablet running free software (FittsStudy Version 4.2.8, default settings) developed by the Accessible Computing Experiences lab (Jacob O. Wobbrock, director) at the University of Washington ([depts.washington.edu/acelab/proj/fittsstudy/index.html](depts.washington.edu/acelab/proj/fittsstudy/index.html)). Participants use a touchscreen pen to tap between ribbons on the screen, with average movement time as the performance metric.

3)  Visuospatial working memory is the capacity to "hold in mind", which researchers have hypothesized to be important in stone toolmaking performance [@coolidge2005]. It also might support a learning process known as 'chunking,' in which multiple items or operations are combined into summary chunks stored in long term memory, that is thought to be important in the acquisition of knapping and other skills [@pargeter2019]. We measured visuospatial working memory using a free n-back task ([wmp.education.uci.edu/software/](https://wmp.education.uci.edu/software/)) developed by the Working Memory and Plasticity Laboratory at the University of California, Irvine (Susanne Jaeggi, PI) and implemented in E-Prime software on a desktop computer. In this task, participants are asked to remember the position of blue squares presented sequentially on the screen and touch a key when the current position matches that 1, 2, 3...n iterations back. Progression to blocks with increasing values of n is contingent on exceeding a threshold success rate. Performance was measured as the highest n achieved.

4)  Fluid intelligence [@cattell1963] refers to the capacity to engage in abstract reasoning and problem solving in a way that is minimally dependent on prior experience. It complements "crystallized intelligence" (the ability to apply learned procedures and knowledge) as one of the two factors (gf, gc) comprising so-called "general intelligence" (g). Fluid intelligence is closely related to the executive control of attention and manipulation of information held in working memory [@engle2018](Engle 2018). It is hypothesized to support technological innovation [@coolidge2005] and/or the intentional learning of new skills [@unsworth2005; @stout2015]. We measured fluid intelligence using the short version [@bilker2012] of the classic Raven Progressive Matrices task, which requires participants to complete increasingly difficult pattern matching questions.  

5)  The use of social information for learning and decision making varies across individuals and societies [@molleman2019]. Such variation is a key topic for understanding social learning and cultural evolutionary processes [@kendal2018; @heyes2018; @miu2020] and represents a potential confound for assessing experimental effects of different social learning conditions. We measured participants' tendency to rely on social information vs. their own insights using the Berlin Estimate AdjuStment Task (BEAST) developed by Molleman et al. [-@molleman2019]. In this task, participants are present with large arrays of items on a screen and asked to estimate the number present. They are then provided with another person's estimate and allowed to provide a second estimate. The participants' average adjustment between first and second estimates provides a measure of their propensity to rely on social information.

## Stone Tool Making

After individual difference testing, participants engaged in a 2-hour stone tool making session, with a 15-minute break after 1 hour. Participants were instructed not to seek out additional training or information on stone tool making (i.e., via the internet) during these breaks. Each group of participants was randomly assigned to one of two experimental conditions: no teaching or teaching. In both conditions, participants were first given an opportunity to inspect and handle examples (**Figure**) of the kind of stone tools (flakes) they are being asked to produce. They were told that their objective was to produce as many flakes as possible from the materials provided. This meant that even the untaught condition included some minimal instruction (being told the objective) , however this was considered to be unavoidable without creating a much more elaborate and naturalistic context in which participants would develop their own technological goals. Such a design would also be expected to increase behavioral variability, demanding correspondingly larger samples of participants to identify patterns and making direct comparisons with the taught condition.

### Raw Materials

Each participant was provided with 9 cores for use over the 2-hour experiment. These cores were produced from larger chunks of a fine-grained basalt purchased from neolithics.com by fracturing them with a sledgehammer. This produced irregular, angular chunks for use in the experiment, weighing between 459g - 1876g (mean = 975g). All cores were weighed, measured (Length, Width, Thickness), and painted white so that new fracture surfaces could be discriminated from those created during production. Cores were sorted by shape and weight and then distributed evenly to each participant. As a result, there were no significant difference across participants in the mean weight (ANOVA, df = 22, F=0.3, p = 0.9; Levene test of homogeneity of variance = 1.04, df1=22, df2 = 184, p = 0.4) or shape (Length x Width/Thickness: ANOVA, df = 22, F=0.4, p = 0.9; Levene statistic = .6, df1=22, df2 = 184, p = 0.9) of cores provided. This was also true comparing the two experimental conditions (Taught vs. Untaught mean weight = 1001g vs. 956g, t = 1.24, df = 205, p = 0.2, Levene's Test F = 0.6, p = 0.4; mean shape = 221.43 vs. 221.45, t = -0.003, df = 205, p = 0.9, Levene's Test F = 3.8, p = 0.05). Participants were, however, allowed to choose which cores to work on so that differences in the weight and shape of cores actually used across participants and conditions could still emerge as a result of selection bias.

Sixty pounds of 3-to-5 inch basalt "Mexican Beach Pebbles" were purchased from a landscaping supply company for use as hammerstones in the experiment. Of these, 90 were selected as suitable for use. These weighed between 213g-1360g (mean = 425) and varied in elongation (L/W = 1.01 to 2.65) and relative thickness (LxW/T = 90.48 to 283.67). Forty-five stones were placed in the middle of the knapping area (Figure 2) for participants to freely choose from during the experiment. Broken hammerstones were replaced from the reserve to maintain a consistent number and range of choices. Each hammerstone was numbered and participants' choices were recorded along with the number of the core(s) being worked on with a particular hammerstone.\

### Experimental Conditions

In both conditions, three researchers were present to record activities and collect materials. Participants were seated in a circle [@shea2015] and experiments were video recorded using two cameras (Figure 1). Participants were free to select hammerstones from the common pile and to work on any or all of their nine assigned cores in any order they preferred. However, each core and all associated debitage were collected before participants were allowed to start working on a new core, so it was not possible to partially work and then return to a particular core later. The order of cores used and associated hammerstones were recorded for each participant during the experiment.

In the untaught condition, a researcher (DS) sat with the participants and made stone tools but remained silent and made no effort to facilitate learning (e.g., through gesture, modified performance, facial expression, attention direction, or verbal instruction). Over the 2-hour period, the researcher completely reduced four cores (one every \~30 minutes). Participants were not restricted from talking to each other, as this would create an unnatural and potentially stressful social context that might affect learning. Participants were asked to avoid any form of communication about the tool making task specifically, and they complied with this request. Participants in this condition thus had the opportunity to observe tool making by an expert and/or by other learners, should they choose to do so, but received no intentional instruction.

In the Taught condition, there were no restrictions on participant interaction and the researcher engaged in direct active teaching [@kline2015] of tool-making techniques through verbal instruction, demonstration, gesture, and shaping of behavior. The instructor has a moderate level of experience teaching basic knapping skills to students in undergraduate archaeology classes and to participants in previous knapping research [e.g., @stout2011]. The pedagogical strategy employed was based on the instructor's own learning experiences and theoretical interpretations [e.g., @pargeter2020], and focused on coaching participants in effective body postures, movement patterns, and grips as well as the assessment of viable core morphology.

## Lithic Analysis

All finished cores were weighed and measured (L, W, T). Delta weight was calculated as (Start weight-End weight)/Start weight. All detached pieces (DPs) were collected and weighed. We did not sort DPs into types (e.g., whole flakes, fragments) as this would have greatly increased processing time and it is not clear that such distinctions add relevant information regarding utility/desirability beyond that supplied by metrics [@stout2019]. All DPs larger than 40mm in maximum dimension were photographed and measured. It is conventional in Early Stone Age lithic analysis to employ a 20 mm cut-off. We selected a higher threshold for both pragmatic (analysis time) and theoretical reasons. Flake use experiments have shown that flakes weighing less than 5--10 g or with a surface area below 7--10 cm2 [@prasciunas2007] or with a maximum dimension \<50-60 mm [@key2014] become markedly inefficient for basic cutting tasks. Similarly, data from Oldowan replication experiments [@stout2019] show that the utility index (flake cutting edge/flake mass1/3) \* (1 - exp[-0.31 \* (flake maximum dimension -- 1.81)]) developed by Morgan et al. (2015) falls off rapidly below 40mm maximum dimension ( Mean Utility \< 40mm = 0.508; \>=40mm = 0.946; t= 11.99, df = 707, p \< 0.000). By including weight in our cut-off criteria we also avoid skewing the flake shape distribution by selectively retaining long, thin pieces (i.e., MD \> 40, weight \< 5g) while discarding rounder pieces of similar (or greater) weight and area.

For measurement, DP length was defined as the longest axis and width as the maximum dimension orthogonal to length. Thickness was defined as the maximum dimension orthogonal to the plane formed by L and W and was measured using calipers. L, W, and plan-view area measurements were taken from photographs captured using a Canon Rebel T3i fitted with a 60 mm macro lens and attached to a photographic stand with adjustable upper and lower light fittings. The camera was positioned directly above the flakes and kept at a constant height. DPs were positioned irrespective of any technological features so that the longest axis was vertical, and the wider end was placed toward the bottom of the photograph.

Photographs were post-processed using Equalight software to adjust for lens and lighting falloff that result from bending light through a lens and its aperture which can affect measurements taken from photographs. Each image was shot with a scale that was then used to rectify the photograph's pixel scale to a real-world measurement scale in Adobe Photoshop. Images were converted to binary black and white format and silhouettes of the tools were extracted in Adobe Photoshop. We then used a custom ImageJ [@rueden2017] script [@pargeter2019] to measure DP length and take nine width measurements at 10% increments of length starting at the base of each DP. We used the built-in ImageJ tool to measure DP area. A "Proportion Larger DPs" was calculated per core as the combined weight of all DPs \>40mm in maximum dimension and 5g in weight divided by the weight of all DPs. Higher values show cores with proportionally more large DPs.

## Statistical Analyses

To evaluate the association between psychometric, motor-skill, and training measures and technological outcomes, we adopted an information-theoretic approach [@burnham2002]. Information-theoretic approaches provide methods for model selection using all possible combinations of variables while avoiding problems associated with significance-threshold stepwise selection. We used the corrected Akaike information criterion (AICc) to rate each possible combination of predictors on the balance between goodness of fit (likelihood of the data given the model) and parsimony (number of parameters). The AICc consists of the log likelihood (i.e., how well does the model fit the data?) and a penalty term for the number of parameters that must be estimated in the model (i.e., how parsimonious is the model?), with a correction for small sample sizes (AICc converges to the standard AIC at large samples). A lower AICc indicates a more generalizable model and we used it to compare and rank various possible models. Each analysis begins with a full model that includes all predictors of interest. All possible combinations of predictors are then fit, and the resulting models are ranked and weighted based on their AICc. The "best" model is chosen because it has the lowest AICc score.

Continuous predictors were centered such that zero represents the sample average, and units are standard deviations. The full model was fitted with the lm function in R 3.2.3, and the glmulti package [@Bartoń 2015] was used for multi-modal selection and model comparison.

\

# Results

Following a recent protocol to enhance the reproducibility and data transparency of archaeological research [@marwick2017], detailed results of all analyses and assessments of the data structure are available in our paper's supplementary materials and through Github (<https://github.com/Raylc/PaST-pilot>). Here we limit discussion to the major ﬁndings regarding flaking performance and individual differences. The purpose of this section is to determine whether training impacted subject flaking performance and if any of the subject's individual psychometric and motor-skill aptitudes predict flaking performance.

## Principal Component analyses

The following two sections outline factor analyses designed to summarize our main study metrics tracking individual variation in flake sizes and shapes and lithic performance measures.

### Detached Piece size and shape

To better understand the relationship between flake shape and training/individual variation, we entered our nine flake linear plan measurements along with maximum flake length and thickness into a principal component analysis (PCA) from which summary coordinates were extracted. Bartlett's Test of Sphericity was significant ($\chi ^2$ (10) =4480, p \< .01) indicating that the set of variables are adequately related for factor analysis.

The analysis yielded three factors explaining a total of 90% of the variance for the entire 11 measurement variable set **(Table**). Factor 1 tracks flake size with higher scores indicating larger flakes since all 11 measures load positively on this factor. Factor 2's loadings track the increasing relationship between thickness, length, and flake width. As factor 2 scores increase, flakes get thicker, longer, and narrow, resembling irregular splinters. Factor 3 tracks the relationship between flake proximal and distal width relative to thickness. As factor 3 scores go up, flakes get thinner and narrower at the distal ends and wider at the base. Factor 3 therefore tracks flakes with a typical shape having a thin cross-section, wider base, and narrower tip. We used these three flake shape coordinates to approximate flake size and shape in the project's flake performance factor analysis.

### Lithic flaking performance measures

To better understand the relationship between our various lithic performance measurements and to reduce these data dimensionality, we conducted a second principal component analysis examining the study's seven lithic performance measures (mass of flakes relative to flaked core mass, count of large flakes [\>40mm and 5g], core delta mass, three flake shape factors, and the total number of cores used). All of these measures except the total cores flaked were summarized for each core. The Bartlett's Test of Sphericity was significant ($\chi ^2$ (6) =3950, p \< .01) indicating that the set of variables are at least adequately related for factor analysis.

The analysis yielded two factors explaining a total of 52.3% of the variance for the entire set of variables. Factor 1 tracks flaking quantity due to high positive loadings on mass flakes/flaked mass, core delta mass, total cores used, and flake shape factor 2. Negative loadings on flake factor 1 (flake size) and 3 (basal/tip width shape) suggest that flaking quantity comes at the expense of producing lots of small and thick stone splinters/chunks. This first factor explained 28% of the variance. Higher factor 1 values reflect higher flaking quantities. The second factor covers 24% of the sample variance. Factor 2 measures one's ability to carefully flake cores due to high positive loadings on large flake count and lower or neutral loadings on mass flakes/flaked mass, core delta mass, and total cores used. The resulting flakes are larger, relatively thinner, and more typically shaped due to high positive loadings on flake factor 1 (size) and flake factor 2 (relative thickness) contrasted with a high negative loading on flake shape factor 3 (basal/tip width). Higher factor two values show increased quality flaking performance.

**Figure** shows the covariance between our two flake performance principal components. While there is no significant relationship between the two factors, and the two study groups do not show significantly different slopes (p = 0.3), there are never-the-less differences between the two groups. Trained individuals are able to increase flake quality while increasing flake quality, whereas untrained individuals increase their flaking quantity at the expense of flake quality.

## Relationships between Performance Measures

This approach also allowed us to compare the relationship between Total Productivity, Quantity, and Quality across our two experimental groups (Figures). As might be expected, we found that per-core Quantity and Total Productivity are positively correlated in both groups (Fig. Xa), although this relationship is twice as strong in the trained (F[1, 9] = 33, p \< 0.01, Adj. R2 = 0.8) compared to untrained (F[1, 8] = 8, p = 0.02, Adj. R2 = 0.4) group. Interestingly, we also found evidence of a negative correlation between Total Productivity and Quality in the untrained group (F[1, 8] = 28, p = \<0.01, Adj. R2 = 0.7), but no relation in the Trained group (Fig. Xb). A qualitatively similar trend with respect to Quality vs. Quantity (Fig. Xc) did not achieve significance (F[1, 17] = 0.6, p 0.2).

Thus, it appears that Trained participants achieved higher Total Productivity by increasing average flaking Quantity across cores and without sacrificing Quality, whereas Untrained participants found other ways to vary Total Productivity (e.g., number of cores knapped rather than Quantity per core, see variance Table and Figure) and generally increased productivity at the expense of Quality. Experimental artifacts illustrating these trade-offs are presented in Figure.

## Do trained, untrained, and expert knappers perform differently?

Here we compare our flaking outcomes (flake size/shape and flaking performance factors) between the trained and untrained groups to see if training in any way impacted their flaking performance. We added a performance comparison (individual flake and core knapping performance metrics) between these two novice groups and our expert knapper to test for differences at different points in the stone flaking skill spectrum.

**Table** summarizes the group level performance tests. The results show no significant differences in flaking performance between the trained and untrained groups measured by our two flaking performance factors. Trained and untrained individuals overall performed equally as well in terms of flaking quality and quantity. Three-way flake size and shape comparisons between our expert knapper and the two novice groups show significant differences in flake shape factor 2 (relative thickness), but with a very low (\<0.01) effect size. This difference is driven by the expert's lower overall relative flake thickness. Regardless of training, our experimental subjects produced flakes that were on average the same size and shape as those of the expert trainer. We did, however, find several significant differences in the three-way comparisons of our individual flaking performance measures. The expert knapper made significantly more large flakes (effect size = 0.14), had a significantly higher core delta mass signal than either of the novice groups (effect size = 0.26), and on average had significantly smaller cores (effect size = 0.27) (**Figure**). All three of these results show either medium or large effect sizes. In all three comparisons, the trained group's data distributions tended towards the expert sample (although they were not significantly different from the untrained group) (**Figures-Core examples too**). These results show that core reduction intensity and large flake production track this experiment's greatest differences between expert and novice performance.

## Does performance change over time?

Here we use the relative order in which each subject flaked their cores to test for changes in flaking performance across the 2hr experiment. For these analyses, we calculated the relative percentage for each core relative to the total cores knapped by each subject. These relative core use-order percentages were then binned into 20 percent brackets for core-order and group-level comparisons. Flaking outcomes were tracked using the two flake performance factors (quality and quantity flaking). We added the nodule starting mass to track whether training/practice times impacted raw material selection.

**Table** shows no significant training effects across the two flaking performance measures either as grouped data or between individuals (**Figures)**. This result demonstrated that flaking outcomes did not change dramatically across the study interval. The one significant main training effect related to core starting mass (with a strong main training effect size = 0.25). On average, core starting masses increase as subjects flake more cores, showing that subjects started with smaller nodules first that were smaller and easier to hold/flake. As the experiment wore on, they were left with larger and more challenging nodules. The small main effect of training condition is driven by higher starting nodule masses in the untrained group at the beginning, half way through, and at the end of the experiment.

## Do individual differences in motor skill and psychometric measures predict flaking performance?

One of the experiment's primary goals was to test if measures of individual variation in motor skill and intelligence/motivation predict success in stone flaking. To address this goal, we built two multivariate models examining the relations between our various psychometric measures, subject's motor skill scores, and our two lithic performance factors (quantity flaking and quality flaking). These models enabled us to determine which of the psychometric and motor skill factors are better predictors of a participant's flaking performance in the study.

We have already demonstrated that subjects selected progressively larger nodules throughout the experiment. It is important now to understand whether nodule variability had any impact on our flaking results. Because starting nodule size (mass) and shape were strongly correlated (F [1,157] = 186, p \< 0.01, R2 = 0.54) we included nodule mass as a covariate to control for any variance in flaking performance that may be driven by nodule differences. Our two motor skill and strength measures (grip strength and Fitt's performance scores) are also strongly correlated (F [1,19] = 15, p \< 0.01, R2 = 0.41). However, these two measures track complementary components of athleticism (strength vs. speed/accuracy tradeoffs) and so we decided to include both in the model selection process.

We considered all possible interactions between five individual difference measures, core size, training condition, and the two lithic flaking performance factors (quantity and quality flaking) (wherein each subject provides one data point). Each model's continuous predictors (highest n-back level, Raven's Progressive Matrix score, BEAST score, starting nodule mass, Fitt's score, and grip strength) were centered such that zero represents the sample average, and units are standard deviations.

### Model 1: Individual differences and quantity flaking

The first full model examined variance in the quantity of flaking tracked by our first performance factor explaining increases in the number of cores used, the degree of reduction on each core, and large/relatively thick flake production. The full model was fitted with the lm function in R 3.2.3, and we used the Glmulti package's automated model selection algorithm to select the best performing model (lowest AICc score) (see methods for further details on the multimodal selection process). The complete model statement is as follows:

*Quantity flaking* $\sim$ Training condition + Highest n-back level + Raven's Progressive Matrix score + BEAST score + Fitt's score + Grip strength

From a candidate pool of 55893 possible multivariate models, the best performing model returned an AICc value of 36 (Average AIC = 52). This model comprised the following statement with three main and four interaction effects:

*Quantity flaking* $\sim$ Training condition + Highest n-back level + BEAST score + Grip strength + Fitt's score$\cdot$Raven's Progressive Matrix score + Training condition$\cdot$Highest n-back level + Training condition$\cdot$BEAST score + Nodule mass (as control)

This model explains a statistically significant and substantial proportion of variance in quantity flaking (R2 = 0.84, F (8, 12) = 8.2, p \< 0.01, adj. R2 = 0.74). A model evaluation comparing training vs. test data subsets shows no evidence for overfitting (Difference in R2 between training and test models = 0.02). A model residuals normality test shows no significant differences with the normal distribution (p = 0.35) indicating that this relationship (as required) is linear. A Breusch-Pagan test showed no evidence for heteroskedasticity (whether variance for all observations in our data set are the same) (BP = 8.2, df = 7, p = 0.3).

\
**Table** presents this model's coefficients and summary outputs, wherein baseline refers to the untrained condition with all continuous predictors at the sample average. The parameter estimates for the continuous predictors reflect the expected change in utility for 1 standard deviation change in the predictor variable. Significant increases in quantity flaking were found for subjects with training (Est. = 0.63 [0.15, 1.11]), higher n-back levels (Est. = 0.71 [0.29, 1.13]), grip strength (Est. = 0.66 [0.36, 0.95]), and BEAST scores (Est. = 0.41 [0.04, 0.78]) regardless of starting nodule sizes (**Figure**). This suggests that several independent factors tracking the effects of training, social information use, visuo-spatial working memory, and strength improve an individual's ability to flake in greater quantities.

The model produced two significant interactions between training condition and n-back level and BEAST scores. Subjects in the trained group with higher n-back levels show lower quantity flaking scores (Est. = -1.35 [-1.85, -0.84]) while subjects in the trained group with higher BEAST scores also show lower quantity flaking scores (Est. = -0.83 [-1.37, -0.28]) when all the other variables are held constant. At first glance, these results appear to contrast with expectations regarding the effects of visuo-spatial working memory and social information use on success in technological tasks. However, looking at the matter more holistically it is clear that untrained subjects produce flaking quantities in a different way that relies on visuo-spatial working memory rather than taught information. When teaching is provided, being aware of one's surroundings (i.e. copying from other novices) can have a negative effect on flaking quantity. The interaction between BEAST scores and training shows that social information use acts to level the effects of an individual's propensity to "muscle" through the flaking task (both groups converge on an average quantity flaking score with higher BEAST scores). However, the direction of this change is different depending on training with untrained and socially inclined individuals increasing flaking quantities in contrast to trained and socially inclined individuals decreasing flaking quantities.

### Model 2: Individual differences and quality flaking

Our second model examining variance in quality flaking follows the same complete model statement we used for the quantity flaking with six covariates. From the same candidate pool size of 55893 possible multivariate models, the best performing model returned an AICc value of 32 (Average AIC = 41). This model comprised the following statement with three main and four interaction effects:

*Quality flaking* $\sim$ Highest n-back level + Fitt's score + Grip strength + Fitt's score$\cdot$BEAST score + Grip strength$\cdot$BEAST score + Grip strength$\cdot$Fitt's score + Training condition$\cdot$Grip strength + Nodule mass (as control)

This model explains a statistically significant and substantial proportion of variance in careful flaking (R2 = 0.78, F (8, 12) = 5.5, p \< 0.01, adj. R2 = 0.64) in the absence of any main training effects. A model evaluation comparing training vs. test data subsets shows some evidence for overfitting (Difference in R2 between training and test models = 0.17), which is unfortunately unavoidable with our small sample sizes. A model residuals normality test shows no significant differences with the normal distribution (p = 0.13) indicating that this relationship is linear. A Breusch-Pagan test showed no evidence for heteroskedasticity (BP = 3.4, df = 8, p = 0.9).

\
**Table** presents this model's coefficients and summary outputs following the same data format as **Table**. The results show three significant main effects between our measures of motor-skill, strength, visuo-spatial working memory, and quality flaking. A one unit increase in Fitt's score (Est. = -0.7 [-1.08, -0.31]), grip strength (Est. = -0.9 [-1.32, -0.53]), visuo-spatial working memory (n-back level) (Est. = -0.3 [-0.58, -0.07]), and nodule starting mass (Est. = -0.3 [-0.58, -0.04]) results in decreased flaking quality regardless of training. Collectively, these results show that quality flaking comes at a cost in terms of a subject's motor abilities and that quality flaking decreases as subjects are faced with flaking larger and more challenging nodules.

The quality flaking model shows two significant interaction effects involving grip strength, BEAST scores, and training. The interaction between grip strength and BEAST scores has a significant positive effect on careful flaking (Est. = 0.5 [0.22, 0.86]). **Figure** illustrates this interaction whereby a subject's propensity to use social information mitigates against individual differences in grip strength. Strong subjects with a low propensity to use social information tend to perform worst in terms of quality flaking. This result makes sense if one considers that our quantity flaking model showed how social information equalizes performance levels in trained and untrained subjects.

The second interaction involves grip strength and training. A one unit increase in this interaction results in a significant positive effect on careful flaking (Est. = 1 [0.51, 1.47]), but only in the untrained group. **Figure** illustrates this interaction showing how training helps even out flaking performance differences between stronger and weaker individuals. Stronger individuals perform worse in terms of quality flaking when they are untrained. Trained subjects, regardless of grip strength, perform equally well in terms of quality flaking.

### Model 3: Individual differences and quality flaking

## Behavioral observations

We designed this exploratory study primarily to trial experimental design elements such as training time, conditions, and raw materials and to collect preliminary data on the effect of individual differences and training on knapping outcomes. We thus focused on collecting quantitative psychometric and lithic data. However, we also considered that quantifying participant knapping behaviors as well as products could be important for future studies. To support methods development in this regard, we made ad hoc notes on observed behaviors during the experiments and video-recorded all experiments to enable later, more systematic analyses yet to be completed. However, even casual behavior observation was sufficient to reveal an unexpected effect. Whereas all trained participants copied the general posture and technique of the expert (free hand knapping seated in a chair) fully half (6) of the uninstructed participants experimented with or even knapped all of their cores using the floor as a support (Figure). Three of these participants were in the same session, which is also the only group composed of just three individuals. In this group, knapping on the ground appears to have been transmitted from one participant to the other two based on appearance order and the point of gaze of participants.

# Discussion

The most salient finding of our exploratory study is that the presence/absence of teaching clearly impacted knapping performance but did so in nuanced and individually variable ways that have not been explored in previous studies. In fact, we did not observe any significant differences in mean performance between our experimental conditions. Some non-significant tendencies toward enhanced Instructed group performance suggest that a larger participant sample might detect significant effects, but also that the size of any such effects would likely remain small. This could reasonably lead to the conclusion that teaching does not substantially facilitate early stage knapping skill acquisition [cf. @putt2014; @ohnuma1997]. Looking closer, however, we found a number of important teaching effects.

## Variance Reduction

In our experiment, the strongest effects of teaching were to reduce variance (Figure, Table) rather than shift mean values. In particular, teaching acted as a "safety net" that homogenized performance by reducing the frequency of extremely poor outcomes (i.e., learning failures). This finding provides additional support for the hypothesis that teaching would have increased the reliability of Oldowan skill reproduction [@morgan2015] while simultaneously corroborating the view that basic flaking competence can be achieved in its absence [@tennie2017]. Our results thus do not imply that teaching was required or even present during Oldowan times (but see @gärdenfors2017), but rather serve to reinforce the plausibility of co-evolutionary scenarios positing the cost/reliability of technological skill acquisition as a selection pressure favoring the evolution of teaching and language [@stout2010; @morgan2015; @stout2017].

## Knapping Behaviors

The current study complements the transmission chain design of Morgan et al. [-@morgan2015] by finding similar effects in more naturalistic learning contexts. Our design further allowed us to examine individual variation to better understand how teaching produces its effects. Whereas transmission chains are optimized to investigate iterative learning effects [but see @caldwell2020], they necessarily involve a different instructor/model for each participant. We sacrificed this iterative component in order to consider how the presence/absence of teaching affected the behavior of individuals under otherwise standardized learning conditions.

We found that a key impact of teaching was to alter basic flake production strategies, as reflected in the relationship between Total Productivity and detached piece Quality (Fig.Xb). Whereas Untrained participants achieved greater Productivity at the expense of Quality and vice versa, these dimensions were unrelated across Trained participants. Thus, even though Untrained participants achieved the highest values on each metric, only trained individuals managed to maximize both simultaneously. Indeed, a core function of teaching is to reduce the search space that learners must explore and increase the likelihood of discovering globally as opposed to locally optimum solutions [cf. @hinton1996; @stout2013]. In our study, Untrained individuals explored a greater range of basic behavioral variations not seen in the Trained group, including knapping on the floor, concentrating on working just a few cores (2-4, Figure) over the practice period, and showing less constrained nodule size preferences (Figure). It is notable that this variation occurred even in the presence of an observable expert example, suggesting it may be interesting for future experiments to address the impact of social context, expectations, and relationships on observational learning strategies [@kendal2018].

We also found a strong positive effect of Grip Strength on Total Productivity independent of learning condition (Figure). While it is tempting to interpret this with respect to the demands for hand strength specifically, it is important to remember that grip strength is strongly correlated with total muscle strength [@wind2010] and overall fitness [@sasaki2007]. Thus, it is best taken to indicate some importance of fitness generally in increasing the rate and intensity of core reduction by naïve knappers, potentially affecting rate of work and the kinetic energy of the swing as well as the handling of core and hammerstone. It thus provides further support for hypotheses positing stone tool making as a selection pressure on the functional anatomy of hand, arm, and shoulder [e.g., @williams-hatala2018], but initially appears orthogonal to variations in learning condition and knapping behaviors in our study. However, we also found that the effect of Grip Strength on per-core knapping Quantity is dependent on teaching (Figure). The absence of this effect in the uninstructed group reflects the weaker association between Total Productivity and per-core Quality across these participants (Fig.Xa) and shows Grip Strength increased uninstructed Productivity specifically by allowing them to knap more cores rather than to reduce individual cores more heavily. In keeping with this, uninstructed Grip Strength is positively correlated with Total Cores knapped (r2 = 0.54, p = 0.01). Conversely, strength allowed instructed participants to increase their average Quantity per core without affecting the total number of cores knapped (r2 = 0.18, p = 0.165). Thus, strength appears to have achieved its effects on core reduction rate and intensity in different ways, depending on teaching. This difference is likely related to the homogenizing effect of teaching on knapping rate (all instructed participants knapped 6 or more cores) and methods. Subjectively, knapping behaviors of uninstructed participants often appeared more physically demanding (e.g., greater number of non-productive blows, rapid and unregulated battering) which would imply different demands on both strength and aerobic fitness [@williams-hatala2021; @mateos2019]. However, this remains to be systematically investigated.

In this respect, it is also important to note that we do not know how well the knapping objectives and strategies communicated by the expert in our experiment correspond to actual Oldowan goals and behaviors. The instructor has successfully replicated assemblage-level patterning at Gona [@stout2019] but Oldowan behavior is variable across space and time [e.g., @braun2019] and alternative knapping methods might maximize different values (productivity, quality, effort), especially in novices [@putt2015] (Putt 2015). Nevertheless, the effect of instruction to constrain behavioral exploration and homogenize outcomes is clear. We expect that this effect would generalize to the teaching of alternative knapping goals and behaviors, although this remains to be tested.

## Learning Strategies

One major goal of this experiment was to test the viability of a moderate, two-hour, learning period for studies of skill acquisition. Unfortunately, we found that this duration was insufficient to capture learning effects for Oldowan-like flake production. The lack of performance change over the period (Figure) cannot be attributed to a ceiling effect (i.e., rapid task mastery at the outset of the practice period) as participants remained well below expert levels and continued to display the high within-individual variability typical of naïve/novice knapping [@eren2011; @pargeter2019]. This negative result was unexpected but is broadly consistent with evidence that Early Stone Age flaking, while conceptually simple, requires substantial practice for perceptual-motor skill development [@nonaka2010; @stout2015; @pargeter2020]. Future investigations of learning variation across individuals and/or experimental conditions may thus need to incorporate longer practice periods to capture skill acquisition processes. In theory, much shorter knapping trials might be used to assess the variation in initial performance across individuals and under different conditions that is captured in our study. However, the presence of substantial core-to-core variation within individuals cautions against overly brief experiments that might not provide a representative sample. Greater durations also allow for the expression of different learning strategies over time, even in the absence of directional performance change.

At a basic level, learners of any new task must balance investment in task exploration vs. exploitation of knowledge and skills already in hand [@sutton2018]. Premature exploitation risks settling for a sub-optimal local solution whereas continued exploration sacrifices more immediate payoffs. Managing this trade-off is especially challenging for complex, real-world tasks like stone knapping, and is thought to depend on the interplay of uncertainty and reward expectation [@wilson2021]. Teaching and social learning generally have the potential to provide low-cost information about task structure and payoffs [@rendell2010; @kendal2018], which if adopted, would be expected to affect exploration/exploitation decisions. Such adoption is itself known to be influenced by individual cognitive differences, for example if higher fluid intelligence allows observers to better understand observed tasks [@vostroknutov2018] or if individuals vary in their tendency to use and value social information [@toelch2014; @molleman2019].

In our study, we did not observe any effect of fluid intelligence (RPM) on knapping outcomes but did find strong interactions of learning condition with participant visuospatial working memory and social information use tendency (Figure). As expected, uninstructed individuals with higher scores on these dimensions displayed higher Total Productivity and average per-core flaking Quantity (although the effect on n-Back on Quantity did not achieve significance). We attribute these effects to increased ability to hold relevant morphological/spatial information in mind and a tendency to benefit from observing successful strategies of others, including the expert model. In contrast, instructed individuals with higher scores tended to have lower Productivity and Quantity. We interpret this unexpected effect to an increased tendency to privilege exploratory learning behavior over exploitation. In particular, we suggest that trained participants might knap more slowly and less productively if higher working memory capacity inclined them to experiment more with morphological/spatial variables highlighted by the instructor or if a predisposition to use social information use caused them to invest greater time and effort attending to and trying out observed actions and/or instructions. These suggestions remain to be tested by further work.

Unfortunately, the training period in our current experiment was insufficient to capture learning effects and so we have no evidence of the effects of these individual differences and putative exploration/exploitation tradeoffs to the ultimate achievement of expertise. A similar negative effect of instruction on knapping outcomes during early stage learning was reported by Putt et al. [-@putt2014], and has been interpreted to reflect learners experimenting with advanced techniques before they have the perceptual-motor skill to execute them [@whiten2015; @stout2015]. Such effects might be further explored with more detailed behavioral data, as opposed to purely lithic data, and with longer learning periods.

## Limitations and Prospects

Although our exploratory study produced a number of robust results with respect to the effects of instruction and individual differences on lithic products, it is clearly limited by a small sample size, short training duration, and lack of detailed quantification of observed behaviors. These are limitations that can hopefully be addressed in future studies building on the methods and evidence presented here. For example, it is notable that our study failed to document any reliable effects on knapping Quality. Obviously, this might reflect an actual lack of such effects, but it may also indicate a need for more sensitive measures and/or increased sample size and training duration to identify subtle or delayed effects. One aspect of our attempt to balance pragmatic costs and benefits in our study was to test the efficacy of relatively limited lithic analysis. More detailed ongoing analyses of core morphology and debitage features (e.g., typology, cutting edge length, platform dimensions) may yet reveal a more reliable signal of knapping quality. Results of the Quality model in particular also seem to suffer from the uneven distribution and discrete rather than continuous nature of scores on our RPM and n-Back tests. Concerns about the sampling of variation on these dimensions could be addressed with larger samples or by pre-screening participants to ensure more even representation. Alternative psychometric tests (e.g., full rather than short version of the RPM) might also provide more sensitive and continuous measures.

Another major limitation that our study shares with all other published experiments on knapping skill acquisition is that we do not address variation in social and cultural context or in teaching style. Currently, we have little basis other than personal experience/tradition [@callahan1979; @whittaker1994; @shea2015] and theoretical speculation [@stout2013; @whiten2015] from which to assess which pedagogical techniques are most effective even in WEIRD contexts. No study to date has considered how variation in teacher skill [@shea2015] or social relationship to participants might impact learning under different conditions. To properly address these questions would require a major research program, including both cross-cultural comparative studies [@barrett2020] and more naturalistic study designs. While costly, such research would produce results of broad relevance to anthropologists, biologists, psychologists, and sociologists interested in teaching and learning.

# Conclusions

# Acknowledgments

# References
