---
title: Supplementary Data for Testing the motor and cognitive foundations of Paleolithic social transmission
author: 
- Justin Pargeter^[Department of Anthropology, New York University, New York, NY, USA; Palaeo-Research Institute, University of Johannesburg, Auckland Park, South Africa; justin.pargeter@nyu.edu]
- Megan Beney Kilgore^[Department of Anthropology, Emory University, Atlanta, GA, USA; megan.elizabeth.beney@emory.edu]
- Cheng Liu^[Department of Anthropology, Emory University, Atlanta, GA, USA; raylc1996@outlook.com]
- Aditi Majoe^[Indepedent Researcher; am2752@cantab.ac.uk]
- Dietrich Stout^[Department of Anthropology, Emory University, Atlanta, GA, USA; dwstout@emory.edu]
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \linenumbers
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{font=scriptsize}
   - \captionsetup[table]{font=scriptsize}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
---
```{r tab1, echo=FALSE, message=FALSE}
library(tidyverse)
df1<-read.csv(here::here("data/tables/s1.csv"), fileEncoding = 'UTF-8-BOM')
kableExtra::kbl(df1, booktabs = T, caption = "Lithic performance between two groups.") %>%
  kableExtra::kable_styling(latex_options = c("striped", "HOLD_position"), font_size = 7)%>%
kableExtra::row_spec(0, bold = T)
```

```{r tab2, echo=FALSE, message=FALSE}
library(tidyverse)
df2<-read.csv(here::here("data/tables/s2.csv"), fileEncoding = 'UTF-8-BOM')
kableExtra::kbl(df2, booktabs = T, caption = "Flake metrics between two groups.") %>%
  kableExtra::kable_styling(latex_options = c("striped", "HOLD_position"), font_size = 7)%>%
kableExtra::row_spec(0, bold = T)
```

```{r tab3, echo=FALSE, message=FALSE}
library(tidyverse)
df3<-read.csv(here::here("data/tables/s3.csv"), fileEncoding = 'UTF-8-BOM')
kableExtra::kbl(df3, booktabs = T, caption = "Starting nodule metrics between two groups.") %>%
  kableExtra::kable_styling(latex_options = c("striped", "HOLD_position"), font_size = 7)%>%
kableExtra::row_spec(0, bold = T)
```